name: Deploy (Maven)

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Deploy to Github Package Registry
        run: |
          mkdir -p ~/.m2
          printf "<settings><servers><server><id>github</id><username>${{ secrets.GITHUB_USERNAME }}</username><password>${{ secrets.GITHUB_USERTOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy